---
title: "H1B"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    theme: lumen
runtime: shiny
---
```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(stringr)
library(leaflet)
library(scales)

h1b_shiny <- readRDS("/Users/liubeixi/Desktop/Data Science/Project/Shinny/H1B/data/h1b_shiny.rds") %>%
  mutate(LeafletPop = str_c(paste0("<a>", WORKSITE, "</a>"),
                            paste0("Apls.: ",comma(apply_city)),
                            paste0("Prop.: ",percent(Percent)), 
                            sep = "<br/>"),
         LeafletPop2 = str_c(paste0("<a>", WORKSITE, "</a>"),
                            paste0("Avg. Wage: ",comma(wage_city),"$"),
                            paste0("Apls.: ",comma(apply_city)),
                            sep = "<br/>"),
         id = seq.int(nrow(.)))
```
```{r data}
selectedData <- reactive({
  if (is.null(input$map_marker_click))
      return(filter(h1b_shiny,WORKSITE == "NEW YORK, NEW YORK"))
  click <- input$map_marker_click
  
  h1b_shiny %>%
    filter(lat == click$lat & lon == click$lng)
})
```
```{r data2}
selectedData2 <- reactive({
  if (is.null(input$map2_marker_click))
      return(filter(h1b_shiny,WORKSITE == "NEW YORK, NEW YORK"))
  click2 <- input$map2_marker_click
  
  h1b_shiny %>%
    filter(lat == click2$lat & lon == click2$lng)
})
```
```{r box1}
box1 <- reactive({
  selectedData() %>% summarise( staterank = first(applyrank_state))
})
```
```{r box2}
box2 <- reactive({
  selectedData() %>% summarise( cityrankstate = first(applyrank_city_state))
})
```
```{r box3}
box3 <- reactive({
  selectedData() %>% summarise( cityrankus = first(applyrank_city_us))
})
```
```{r box4}
box4 <- reactive({
  selectedData2() %>% summarise( staterank = first(wagerank_state))
})
```
```{r box5}
box5 <- reactive({
  selectedData2() %>% summarise( cityrankstate = first(wagerank_city_state))
})
```
```{r box6}
box6 <- reactive({
  selectedData2() %>% summarise( cityrankus = first(wagerank_city_us))
})
```


Application
=======================================================================
Row
-----------------------------------------------------------------------

### State rank {.value-box}

```{r}
#warn when it ranks top 8
renderValueBox({
  valueBox(
    value = box1(),
    icon = "ion-ios-personadd",
    color = ifelse(box1() <= 8, "warning", "primary")
  )
})
```

### City rank within state {.value-box}

```{r}
#warn when it ranks top 5
renderValueBox({
  valueBox(value = box2(),
           icon = "ion-person-stalker",
           color = ifelse(box2() <= 5, "warning", "primary")
  )
})
```

### City rank all over us {.value-box}

```{r}
#warn when it ranks top 8
renderValueBox({
  valueBox(value = box3(),
           icon = "ion-ios-people",
           color = ifelse(box3() <= 20, "warning", "primary")
  )
})
```

Row
-----------------------------------------------------------------------

### Distribution map {data-width=700}

```{r}
output$map <- renderLeaflet({ 
  leaflet(h1b_shiny) %>% 
  addProviderTiles("CartoDB.Positron") %>%
  fitBounds(~-124.848974, ~24.396308, 
            ~-66.885444, ~49.384358) %>%
  clearShapes() %>%
  clearControls() %>%
  addCircleMarkers( lng = ~lon, lat = ~lat, weight = 1,
                 radius = ~sqrt(Percent)*100, 
                 color = "#022A68", stroke = FALSE,
                 popup =  ~LeafletPop,
                 fillOpacity = 0.6, layerId = ~id)
})

leafletOutput("map")
```

### Top employers {data-width=340}

```{r}
renderTable({
 selectedData() %>%
    select("Employer" = EMPLOYER_NAME,
           "Applications" = apply_employer_city, 
           "Rank" = applyrank_employer_city) %>%
    arrange(Rank) %>%
    as.data.frame() 
}, digits = 1)
```


Salary
=======================================================================
Row
-----------------------------------------------------------------------

### State rank {.value-box}

```{r}
#warn when it ranks top 8
renderValueBox({
  valueBox(
    value = box4(),
    icon = "fa-dollar-sign",
    color = ifelse(box4() <= 8, "warning", "primary")
  )
})
```

### City rank within state {.value-box}

```{r}
#warn when it ranks top 5
renderValueBox({
  valueBox(value = box5(),
           icon = "fa-hand-holding-usd",
           color = ifelse(box5() <= 5, "warning", "primary")
  )
})
```

### City rank all over us {.value-box}

```{r}
#warn when it ranks top 10
renderValueBox({
  valueBox(value = box6(),
           icon = "fa-hands-usd",
           color = ifelse(box6() <= 20, "warning", "primary")
  )
})
```

Row
-----------------------------------------------------------------------

### Distribution map {data-width=700}

```{r}
output$map2 <- renderLeaflet({ 
  leaflet(h1b_shiny) %>% 
  addProviderTiles("CartoDB.Positron") %>%
  fitBounds(~-124.848974, ~24.396308, 
            ~-66.885444, ~49.384358) %>%
  clearShapes() %>%
  clearControls() %>%
  addCircleMarkers( lng = ~lon, lat = ~lat, weight = 1,
                 radius = ~sqrt(Percent)*100, 
                 color = "#0D632A", stroke = FALSE,
                 popup =  ~LeafletPop2,
                 fillOpacity = 0.6, layerId = ~id)
})

leafletOutput("map2")
```

### Top employers {data-width=340}

```{r}
renderTable({
 selectedData2() %>%
    select("Employer" = EMPLOYER_NAME,
           "Avg. Wage" = wage_employer_city, 
           "Rank" = wagerank_employer_city) %>%
    arrange(Rank) %>%
    as.data.frame() 
}, digits = 1)
```